// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4F1rCfnO-3-tT4YloHVAbqGkd7EtgxGk',
    appId: '1:136817731846:web:db078d33161d25478ed687',
    messagingSenderId: '136817731846',
    projectId: 'feelin-pay-c15ac',
    authDomain: 'feelin-pay-c15ac.firebaseapp.com',
    storageBucket: 'feelin-pay-c15ac.firebasestorage.app',
    measurementId: 'G-2CZJNQ1GPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSJf9zUqcoehVa-oz4-Zp0-PCfURfrobQ',
    appId: '1:136817731846:android:16c2dfd65501c97a8ed687',
    messagingSenderId: '136817731846',
    projectId: 'feelin-pay-c15ac',
    storageBucket: 'feelin-pay-c15ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaQDumloaVCySMraXYRGlnO-Spsz9DDf4',
    appId: '1:136817731846:ios:02ec30ca8aa921548ed687',
    messagingSenderId: '136817731846',
    projectId: 'feelin-pay-c15ac',
    storageBucket: 'feelin-pay-c15ac.firebasestorage.app',
    iosBundleId: 'com.example.feelinPay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaQDumloaVCySMraXYRGlnO-Spsz9DDf4',
    appId: '1:136817731846:ios:02ec30ca8aa921548ed687',
    messagingSenderId: '136817731846',
    projectId: 'feelin-pay-c15ac',
    storageBucket: 'feelin-pay-c15ac.firebasestorage.app',
    iosBundleId: 'com.example.feelinPay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4F1rCfnO-3-tT4YloHVAbqGkd7EtgxGk',
    appId: '1:136817731846:web:65db0f3114e515888ed687',
    messagingSenderId: '136817731846',
    projectId: 'feelin-pay-c15ac',
    authDomain: 'feelin-pay-c15ac.firebaseapp.com',
    storageBucket: 'feelin-pay-c15ac.firebasestorage.app',
    measurementId: 'G-ND1L7NK92C',
  );
}
