// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJpAGmHaFkAiPp7_A3zuZEUq8fXJ5kyDM',
    appId: '1:607923304959:web:3ca54d4f1195c44f488fca',
    messagingSenderId: '607923304959',
    projectId: 'feelin-pay-a345a',
    authDomain: 'feelin-pay-a345a.firebaseapp.com',
    storageBucket: 'feelin-pay-a345a.firebasestorage.app',
    measurementId: 'G-34LQ22CS1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNQ-1DPxYE2J0Y_RuObg7KEVJ9dMrNHSo',
    appId: '1:607923304959:android:7cb24de543b51f92488fca',
    messagingSenderId: '607923304959',
    projectId: 'feelin-pay-a345a',
    storageBucket: 'feelin-pay-a345a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg5gR7bbOtp3Pv4lmfqVA8IoKJi5kVabI',
    appId: '1:607923304959:ios:1f4161a079332f92488fca',
    messagingSenderId: '607923304959',
    projectId: 'feelin-pay-a345a',
    storageBucket: 'feelin-pay-a345a.firebasestorage.app',
    iosBundleId: 'com.example.feelinPay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg5gR7bbOtp3Pv4lmfqVA8IoKJi5kVabI',
    appId: '1:607923304959:ios:1f4161a079332f92488fca',
    messagingSenderId: '607923304959',
    projectId: 'feelin-pay-a345a',
    storageBucket: 'feelin-pay-a345a.firebasestorage.app',
    iosBundleId: 'com.example.feelinPay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJpAGmHaFkAiPp7_A3zuZEUq8fXJ5kyDM',
    appId: '1:607923304959:web:5c54a48bac429876488fca',
    messagingSenderId: '607923304959',
    projectId: 'feelin-pay-a345a',
    authDomain: 'feelin-pay-a345a.firebaseapp.com',
    storageBucket: 'feelin-pay-a345a.firebasestorage.app',
    measurementId: 'G-9P2C00RECT',
  );
}
